### PR TITLE
Add feeds view for RSS, Atom & JSON feeds

### LINKED ISSUE #1: (Suggestion) RSS feed viewer!
I absolutely love this thing! have it running on my server display since it really adds an element of information that I was looking for! I definitely want to see where this thing goes in the future! I would suggest looking into the possibility to add another info display for RSS feeds. It would be quite an interesting component to have. With it being a side monitor, RSS feeds can carry a lot of information on their own, and I think it would work great with this!

### PR DESCRIPTION
**Pull request by merlinfuchs**
- Supports multiple sources
- Items are sorted by published time
- You can hide published time and feed title for smaller screens or if you only have one feed
- Automatically computes the max number of items that fit into the view (you can also override it)

grafik

closes #1

### CODE REVIEW

**Comment by merlinfuchs** [comment]
@WyattHBrown Let me know if this is what you were looking for and if you have any more suggestions!

**Comment by WyattHBrown** [comment]
@merlinfuchs That's exactly what I was looking for! Thanks man!
I am having a bit of an issue with trying to run it on my end, the blimp program itself doesn't react to any changes made in the internal code, even if I were to delete all the icons, it doesn't seem to effect the run file. Might just be on my end, but the only file that seems to affect the blimp terminal file is the config.
Apologies for my lack of knowledge, I haven't used Go before haha.

**Comment by merlinfuchs** [comment]
It depends on how you have installed and run blimp. Right now these changes aren't in the master branch yet so you would need to checkout or install from this branch. 
I will merge the changes now so you should be able to install normally from the master branch :)

**Comment by WyattHBrown** [comment]
Awesome! I also realized my issue, I forgot to build the go file when making the changes! Got it all working now!

**Pull request merged**
